2024-12-26 16:42:25.4823 | logger:62 | ERROR | 未捕获的异常
Traceback (most recent call last):

> File "C:\Users\86364\PycharmProjects\fastApiDemo\main.py", line 22, in <module>
    app.include_router(lora_router, prefix="lora_node", tags=["lora节点相关接口"])
    │   │              └ <fastapi.routing.APIRouter object at 0x000001CBEA077580>
    │   └ <function FastAPI.include_router at 0x000001CBEB6534C0>
    └ <fastapi.applications.FastAPI object at 0x000001CBE7F66100>

  File "C:\Users\86364\PycharmProjects\fastApiDemo\venv\lib\site-packages\fastapi\applications.py", line 1447, in include_router
    self.router.include_router(
    │    │      └ <function APIRouter.include_router at 0x000001CBEB616DC0>
    │    └ <fastapi.routing.APIRouter object at 0x000001CBEB9AB100>
    └ <fastapi.applications.FastAPI object at 0x000001CBE7F66100>

  File "C:\Users\86364\PycharmProjects\fastApiDemo\venv\lib\site-packages\fastapi\routing.py", line 1258, in include_router
    assert prefix.startswith("/"), "A path prefix must start with '/'"
           │      └ <method 'startswith' of 'str' objects>
           └ 'lora_node'

AssertionError: A path prefix must start with '/'
2024-12-26 16:45:20.8723 | events:41 | INFO | 开始检查当前环境是否满足配置文件中设备所需全部IP
2024-12-26 16:45:20.8869 | events:50 | INFO | 配置文件中所需的所有设备IP地址: ['192.168.24.114', '192.168.24.115', '192.168.24.116', '192.168.24.117', '192.168.24.118', '192.168.24.119']，对应设备名称: ['channel_camera_ip', 'parking_camera_ip', 'lora_node_ip', 'four_bytes_node_ip', 'network_led_ip', 'network_lcd_ip']
2024-12-26 16:45:20.8869 | events:63 | INFO | 环境满足，开始初始化设备
2024-12-26 16:45:21.0055 | device_manager:65 | INFO | 通道相机设备初始化成功
2024-12-26 16:45:21.0351 | device_manager:76 | INFO | 车位相机设备初始化成功
2024-12-26 16:45:21.0384 | device_manager:86 | INFO | Lora节点初始化成功
2024-12-26 16:45:21.0384 | services:244 | INFO | 车位相机收到服务器的车位状态上报返回：{'protocol_head': '0xfb', 'timestamp': 1735202721, 'command_code': 'S', 'total_packets': 1, 'packet_number': 0, 'data_length': 1, 'data_content': '\x00', 'checksum': 481, 'protocol_tail': '0xfe'}
2024-12-26 16:45:21.0404 | device_manager:96 | INFO | 四字节网络节点初始化成功
2024-12-26 16:45:21.0435 | device_manager:107 | INFO | 网络led屏初始化成功
2024-12-26 16:45:21.0866 | device_manager:118 | INFO | 网络lcd一体屏初始化成功
2024-12-26 16:45:21.0866 | events:66 | INFO | 所有设备初始化成功
2024-12-26 16:45:21.1593 | events:73 | INFO | sqlite初始化成功
2024-12-26 16:45:21.1871 | services:82 | INFO | LCD一体屏收到来自服务器的指令 {'code': 5000, 'message': '屏地址[24119119]有误，未查询到屏信息！', 'data': ''}
2024-12-26 16:45:21.1882 | services:91 | INFO | LCD一体屏指令响应包发送成功，reqid：None
2024-12-26 16:45:21.2113 | services:95 | INFO | LCD一体屏录入接收到的下发指令到数据库成功{"code":5000,"message":"屏地址[24119119]有误，未查询到屏信息！","data":""}
2024-12-26 16:46:51.0338 | services:114 | INFO | 通道相机收到服务器下发数据，解包结果: {'protocol_head': '0xfb', 'timestamp': 1735202815, 'command_code': '»', 'total_packets': 21504, 'packet_number': 256, 'data_length': 0, 'data_content': '', 'checksum': 22139, 'protocol_tail': '0x22'}
2024-12-26 16:46:51.0667 | services:100 | INFO | LED网络屏收到服务器下发的未知类型数据，解包结果: {'protocol_head': '0xfb', 'timestamp': 1735202815, 'command_code': '»', 'total_packets': 17920, 'packet_number': 256, 'data_length': 0, 'data_content': '', 'checksum': 2, 'protocol_tail': '0x2d'}
2024-12-26 16:46:51.0667 | services:246 | INFO | 车位相机收到服务器下发数据，解包结果: {'protocol_head': '0xfb', 'timestamp': 1735202815, 'command_code': '»', 'total_packets': 17920, 'packet_number': 256, 'data_length': 0, 'data_content': '', 'checksum': 2, 'protocol_tail': '0x2d'}
